[custom]
;==========================================================
; 1. 基础配置
;==========================================================
enable_rule_generator=true
overwrite_original_rules=true

;==========================================================
; 2. 策略组 (Proxy Groups)
; 格式: 名字`类型`包含节点`测速地址`间隔`容差
;==========================================================
custom_proxy_group=节点选择`select`[]香港节点`[]新加坡节点`[]日本节点`[]台湾节点`[]美国节点`[]欧洲节点`[]全部节点`[]自建/家宽节点`[]故障转移
custom_proxy_group=🤖 人工智能`select`[]节点选择`[]香港节点`[]新加坡节点`[]日本节点`[]台湾节点`[]美国节点`[]欧洲节点`[]全部节点`[]全球直连
custom_proxy_group=💬 国外社交`select`[]节点选择`[]香港节点`[]新加坡节点`[]日本节点`[]台湾节点`[]美国节点`[]欧洲节点`[]全部节点`[]全球直连
custom_proxy_group=🎬 国外媒体`select`[]节点选择`[]香港节点`[]新加坡节点`[]日本节点`[]台湾节点`[]美国节点`[]欧洲节点`[]全部节点`[]全球直连
custom_proxy_group=全球直连`select`[]DIRECT`[]🔗 代理`[]全部节点
custom_proxy_group=隐私拦截`select`[]REJECT`[]REJECT-DROP`[]DIRECT`[]🔗 代理
custom_proxy_group=🐟 漏网之鱼`select`[]节点选择`[]香港节点`[]新加坡节点`[]日本节点`[]台湾节点`[]美国节点`[]欧洲节点`[]全部节点`[]全球直连

custom_proxy_group=香港节点`url-test`(港|hk|hongkong|Hong Kong|🇭🇰)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=新加坡节点`url-test`(新|🇸🇬|SG|singapore)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=日本节点`url-test`(日本|🇯🇵|JP|Japan)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=台湾节点`url-test`(台|🇹🇼|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=美国节点`url-test`(美|🇺🇲|🇺🇸|US|America|United States|Los Angeles|Chicago|Ashburn|Seattle|Kansas)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=欧洲节点`url-test`(🇦🇱|🇦🇩|🇦🇹|🇧🇾|🇧🇪|🇧🇦|🇧🇬|🇭🇷|🇨🇾|🇨🇿|🇩🇰|🇪🇪|🇫🇮|🇫🇷|🇩🇪|🇬🇷|🇭🇺|🇮🇸|🇮🇪|🇮🇹|🇽🇰|🇱🇻|🇱🇮|🇱🇹|🇱🇺|🇲🇹|🇲🇩|🇲🇨|🇲🇪|🇳🇱|🇲🇰|🇳🇴|🇵🇱|🇵🇹|🇷🇴|🇷🇺|🇸🇲|🇷🇸|🇸🇰|🇸🇮|🇪🇸|🇸🇪|🇨🇭|🇹🇷|🇺🇦|🇬🇧|🇻🇦)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=全部节点`url-test`.*`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=自建/家宽节点`select`(自建|CF|The_house|private|home|家宽|hgc|HKT|HKBN|icable|Hinet|att)
custom_proxy_group=故障转移`fallback`.*`http://www.gstatic.com/generate_204`300
custom_proxy_group=🔗 代理`select`[]节点选择

;==========================================================
; 3. 规则集提供者 (Rule Providers) 
;==========================================================
; 广告拦截
rule_provider=banAd_domain,domain,https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/banAd_mini.mrs,86400

; 人工智能
rule_provider=ai!cn_domain,domain,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs,86400
rule_provider=ai_domain,domain,https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/ai.mrs,86400
rule_provider=openai_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/openai.mrs,86400

; 国外社交
rule_provider=telegram_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs,86400
rule_provider=telegram_ip,ipcidr,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs,86400
rule_provider=meta_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/meta.mrs,86400
rule_provider=facebook_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/facebook.mrs,86400

; 国外媒体
rule_provider=youtube_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs,86400
rule_provider=netflix_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs,86400
rule_provider=disney_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/disney.mrs,86400
rule_provider=spotify_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/spotify.mrs,86400

; 全球直连
rule_provider=direct_domain,domain,https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/direct.mrs,86400
rule_provider=cn_domain,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs,86400
rule_provider=cn_ip,ipcidr,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs,86400

;==========================================================
; 4. 路由分流规则 (Rules)
;==========================================================
custom_rule=RULE-SET,banAd_domain,隐私拦截

custom_rule=RULE-SET,ai!cn_domain,🤖 人工智能
custom_rule=RULE-SET,ai_domain,🤖 人工智能
custom_rule=RULE-SET,openai_domain,🤖 人工智能

custom_rule=RULE-SET,telegram_domain,💬 国外社交
custom_rule=RULE-SET,telegram_ip,💬 国外社交,no-resolve
custom_rule=RULE-SET,meta_domain,💬 国外社交
custom_rule=RULE-SET,facebook_domain,💬 国外社交

custom_rule=RULE-SET,youtube_domain,🎬 国外媒体
custom_rule=RULE-SET,netflix_domain,🎬 国外媒体
custom_rule=RULE-SET,disney_domain,🎬 国外媒体
custom_rule=RULE-SET,spotify_domain,🎬 国外媒体

custom_rule=RULE-SET,direct_domain,全球直连
custom_rule=RULE-SET,cn_domain,全球直连
custom_rule=RULE-SET,cn_ip,全球直连,no-resolve
custom_rule=GEOIP,CN,全球直连

custom_rule=MATCH,🐟 漏网之鱼
